/**
 * Seed script for QuickSkill v2.
 *
 * Populates Firestore with expanded skills, topic-tagged questions,
 * learning explanations, and varied interaction types.
 *
 * Usage:
 *   1. Set FIREBASE_SERVICE_ACCOUNT_PATH in .env
 *   2. Run: npm run seed
 */

import { readFileSync, existsSync } from 'fs';
import { createRequire } from 'module';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

function loadEnv() {
  const envPath = resolve(__dirname, '..', '.env');
  if (!existsSync(envPath)) return;
  const content = readFileSync(envPath, 'utf-8');
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const value = trimmed.slice(eqIdx + 1).trim();
    if (!process.env[key]) process.env[key] = value;
  }
}

loadEnv();

const require = createRequire(import.meta.url);
const admin = require('firebase-admin');

const serviceAccountPath =
  process.env.FIREBASE_SERVICE_ACCOUNT_PATH ||
  process.env.GOOGLE_APPLICATION_CREDENTIALS;

if (!serviceAccountPath) {
  console.error('Error: FIREBASE_SERVICE_ACCOUNT_PATH must be set.');
  process.exit(1);
}

const resolvedPath = resolve(__dirname, '..', serviceAccountPath);
let serviceAccount;
try {
  serviceAccount = JSON.parse(readFileSync(resolvedPath, 'utf-8'));
} catch {
  try { serviceAccount = require(resolvedPath); } catch {
    console.error('Error: Could not load service account from:', resolvedPath);
    process.exit(1);
  }
}

admin.initializeApp({ credential: admin.credential.cert(serviceAccount) });
const db = admin.firestore();

const skills = [
  // ─── 1. Pattern Recognition ──────────────────────────────────
  {
    name: 'Pattern Recognition',
    description: 'Train your brain to detect logical patterns, sequences, and relationships. Each question builds your ability to spot what comes next.',
    enhances: 'Logic, Analytical Thinking, Pattern Detection',
    example: 'Complete the sequence: 2, 6, 18, 54, ?',
    type: 'cognitive',
    difficulty: 'easy',
    topic: 'patterns',
    questionBank: [
      {
        questionText: 'What number comes next? 2, 6, 18, 54, ?',
        options: ['108', '162', '72', '90'],
        correctAnswer: '162',
        topic: 'number-patterns',
        explanation: 'Each number is multiplied by 3. 2×3=6, 6×3=18, 18×3=54, 54×3=162.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Which letter comes next? A, C, F, J, ?',
        options: ['O', 'N', 'M', 'P'],
        correctAnswer: 'O',
        topic: 'letter-patterns',
        explanation: 'The gaps increase by 1 each time: A→C (+2), C→F (+3), F→J (+4), J→O (+5).',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Find the odd one out: 3, 9, 27, 45, 81',
        options: ['3', '9', '27', '45'],
        correctAnswer: '45',
        topic: 'number-patterns',
        explanation: 'All are powers of 3 (3¹=3, 3²=9, 3³=27, 3⁴=81). 45 is not a power of 3.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Complete: Monday → 1, Wednesday → 3, Friday → ?',
        options: ['5', '6', '7', '4'],
        correctAnswer: '5',
        topic: 'sequence-detection',
        explanation: 'Days of the week numbered: Monday=1, Tuesday=2, Wednesday=3, Thursday=4, Friday=5.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What comes next in the pattern: △, ◯, □, △, ◯, ?',
        options: ['□', '△', '◯', '☆'],
        correctAnswer: '□',
        topic: 'visual-patterns',
        explanation: 'The pattern repeats every 3 shapes: triangle, circle, square. After triangle, circle, the 6th is square.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'If 1=3, 2=6, 3=9, 4=?',
        options: ['12', '10', '16', '8'],
        correctAnswer: '12',
        topic: 'number-patterns',
        explanation: 'Each number is multiplied by 3: 1×3=3, 2×3=6, 3×3=9, 4×3=12.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Type the next number: 1, 4, 9, 16, 25, ?',
        correctAnswer: '36',
        topic: 'number-patterns',
        explanation: 'These are perfect squares: 1²=1, 2²=4, 3²=9, 4²=16, 5²=25, 6²=36.',
        interactionType: 'text-input',
      },
      {
        questionText: 'Which word completes the pattern? Run, Running, Ran, ?',
        options: ['Run', 'Runner', 'Running', 'Runs'],
        correctAnswer: 'Runner',
        topic: 'word-patterns',
        explanation: 'The pattern shows different forms: base (Run), gerund (Running), past (Ran), noun (Runner).',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What is the missing number? 2, 3, 5, 7, 11, ?, 17',
        options: ['13', '12', '14', '15'],
        correctAnswer: '13',
        topic: 'number-patterns',
        explanation: 'These are prime numbers. After 11, the next prime is 13.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Solve the pattern: ▲+▲ = 4, ▲+● = 7, ●+● = ?',
        options: ['10', '8', '6', '14'],
        correctAnswer: '10',
        topic: 'visual-patterns',
        explanation: '▲=2 (since 2+2=4). Then 2+●=7 means ●=5. So ●+● = 5+5 = 10.',
        interactionType: 'multiple-choice',
      },
    ],
  },

  // ─── 2. Vocabulary Builder ───────────────────────────────────
  {
    name: 'Vocabulary Builder',
    description: 'Expand your word knowledge with definitions, synonyms, and contextual usage. Learn the meaning behind each word.',
    enhances: 'Vocabulary, Communication, Reading Comprehension',
    example: 'What does "ubiquitous" mean?',
    type: 'vocabulary',
    difficulty: 'easy',
    topic: 'vocabulary',
    questionBank: [
      {
        questionText: 'What does "ephemeral" mean?',
        options: ['Lasting for a very short time', 'Extremely large', 'Related to outer space', 'Difficult to understand'],
        correctAnswer: 'Lasting for a very short time',
        topic: 'word-meanings',
        explanation: 'Ephemeral comes from Greek "ephemeros" meaning "lasting only a day." Think of a mayfly that lives for just 24 hours.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What is a synonym for "pragmatic"?',
        options: ['Practical', 'Idealistic', 'Optimistic', 'Dramatic'],
        correctAnswer: 'Practical',
        topic: 'synonyms',
        explanation: 'Pragmatic means dealing with things in a practical, realistic way. A pragmatic person focuses on what works, not what\'s ideal.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What does "ambiguous" mean?',
        options: ['Open to interpretation', 'Clearly defined', 'Extremely fast', 'Deeply emotional'],
        correctAnswer: 'Open to interpretation',
        topic: 'word-meanings',
        explanation: 'Ambiguous means having multiple possible meanings. An ambiguous statement can be understood in different ways.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Choose the correct spelling:',
        options: ['Accommodate', 'Acommodate', 'Accomodate', 'Acomodate'],
        correctAnswer: 'Accommodate',
        topic: 'spelling',
        explanation: 'Accommodate has double C and double M. Think: "I need to Accommodate two Cots and two Mattresses."',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What does "benevolent" mean?',
        options: ['Well-meaning and kindly', 'Extremely wealthy', 'Highly intelligent', 'Very powerful'],
        correctAnswer: 'Well-meaning and kindly',
        topic: 'word-meanings',
        explanation: 'Benevolent comes from Latin "bene" (well) + "volens" (wishing). A benevolent person wishes well for others.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Use "eloquent" in a sentence by typing a short phrase:',
        correctAnswer: 'eloquent speech',
        topic: 'word-usage',
        explanation: 'Eloquent means fluent or persuasive in speaking. A person who speaks clearly and movingly is eloquent.',
        interactionType: 'text-input',
      },
      {
        questionText: 'What is an antonym of "ardent"?',
        options: ['Apathetic', 'Passionate', 'Eager', 'Intense'],
        correctAnswer: 'Apathetic',
        topic: 'antonyms',
        explanation: 'Ardent means passionate or enthusiastic. Apathetic means lacking interest — the direct opposite.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What does "meticulous" mean?',
        options: ['Very careful and precise', 'Careless and hasty', 'Large in size', 'Quick to anger'],
        correctAnswer: 'Very careful and precise',
        topic: 'word-meanings',
        explanation: 'Meticulous comes from Latin "meticulosus" (fearful). A meticulous person is so careful they check every tiny detail.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Type the word that means "to make something seem less important":',
        correctAnswer: 'downplay',
        topic: 'word-usage',
        explanation: '"Downplay" means to make something seem less important than it really is. A similar word is "understate."',
        interactionType: 'text-input',
      },
      {
        questionText: 'Which word is the correct adjective form? "He gave an ___ explanation."',
        options: ['elaborate', 'elaborated', 'elaboration', 'elaboratively'],
        correctAnswer: 'elaborate',
        topic: 'word-forms',
        explanation: '"Elaborate" is the adjective form meaning detailed and complex. "He gave an elaborate explanation" means it was very detailed.',
        interactionType: 'multiple-choice',
      },
    ],
  },

  // ─── 3. Mental Math ──────────────────────────────────────────
  {
    name: 'Mental Math',
    description: 'Sharpen your arithmetic through fast mental calculations. Learn tricks and shortcuts that make math easier every day.',
    enhances: 'Numeracy, Speed Calculation, Memory',
    example: 'Calculate: 15 × 12 = ?',
    type: 'cognitive',
    difficulty: 'easy',
    topic: 'math',
    questionBank: [
      {
        questionText: 'What is 15 × 12?',
        options: ['150', '170', '180', '160'],
        correctAnswer: '180',
        topic: 'multiplication',
        explanation: 'Break it down: 15 × 10 = 150, plus 15 × 2 = 30. Total: 150 + 30 = 180.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What is 25% of 240?',
        options: ['50', '60', '70', '80'],
        correctAnswer: '60',
        topic: 'percentages',
        explanation: '25% is the same as 1/4. 240 ÷ 4 = 60. Tip: to find 25%, just divide by 4.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What is 144 ÷ 12?',
        options: ['10', '11', '12', '13'],
        correctAnswer: '12',
        topic: 'division',
        explanation: '12 × 12 = 144, so 144 ÷ 12 = 12. 144 is also called a "gross" (a dozen dozens).',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What is 7 × 8 + 6?',
        options: ['62', '56', '64', '58'],
        correctAnswer: '62',
        topic: 'order-of-operations',
        explanation: 'Follow PEMDAS/BODMAS: multiplication first (7×8=56), then addition (56+6=62).',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What is the square root of 169?',
        options: ['11', '12', '13', '14'],
        correctAnswer: '13',
        topic: 'squares-roots',
        explanation: '13 × 13 = 169. Tip: memorize squares up to 20² — they appear often in math problems.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What is 99 + 99?',
        options: ['188', '198', '208', '178'],
        correctAnswer: '198',
        topic: 'addition',
        explanation: '99 + 99 = (100 - 1) + (100 - 1) = 200 - 2 = 198. Rounding both numbers to 100 makes it easy.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'If a pizza is cut into 8 slices and you eat 3, what fraction is left?',
        options: ['5/8', '3/8', '5/5', '1/2'],
        correctAnswer: '5/8',
        topic: 'fractions',
        explanation: 'Total slices = 8. You ate 3, so remaining = 8 - 3 = 5. Fraction left = 5/8.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What is 10% of 450?',
        options: ['45', '4.5', '450', '90'],
        correctAnswer: '45',
        topic: 'percentages',
        explanation: '10% means 10 per 100, which is 1/10. 450 ÷ 10 = 45. Tip: to find 10%, just move the decimal one place left.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Type the answer: 2³ + 3² = ?',
        correctAnswer: '17',
        topic: 'exponents',
        explanation: '2³ = 2×2×2 = 8, and 3² = 3×3 = 9. 8 + 9 = 17.',
        interactionType: 'text-input',
      },
      {
        questionText: 'What is the average of 12, 15, and 18?',
        options: ['15', '14', '16', '13'],
        correctAnswer: '15',
        topic: 'averages',
        explanation: 'Average = sum ÷ count. Sum = 12+15+18 = 45. Count = 3. 45 ÷ 3 = 15.',
        interactionType: 'multiple-choice',
      },
    ],
  },

  // ─── 4. Memory Recall ────────────────────────────────────────
  {
    name: 'Memory Recall',
    description: 'Strengthen your short-term and long-term memory through engaging recall exercises with real-world facts.',
    enhances: 'Short-term Memory, Focus, Concentration',
    example: 'Remember and recall a sequence of items',
    type: 'memory',
    difficulty: 'medium',
    topic: 'memory',
    questionBank: [
      {
        questionText: 'What is the 7th digit of pi after the decimal point? (3.1415926...)',
        options: ['6', '5', '9', '2'],
        correctAnswer: '6',
        topic: 'numerical-memory',
        explanation: 'π = 3.1415926535... The 7th digit after the decimal is the 6 (the "2" is 6th, "6" is 7th). Memory aid: "3.141592" — count: 1,4,1,5,9,2,6.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'How many continents are there on Earth?',
        options: ['5', '6', '7', '8'],
        correctAnswer: '7',
        topic: 'geography-memory',
        explanation: 'The 7 continents: Asia, Africa, North America, South America, Antarctica, Europe, Australia.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Which planet is known as the Red Planet?',
        options: ['Venus', 'Jupiter', 'Mars', 'Saturn'],
        correctAnswer: 'Mars',
        topic: 'science-memory',
        explanation: 'Mars appears red because its surface contains iron oxide (rust). That\'s why it\'s called the Red Planet.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What element has the chemical symbol "Fe"?',
        options: ['Iron', 'Silver', 'Gold', 'Copper'],
        correctAnswer: 'Iron',
        topic: 'science-memory',
        explanation: 'Fe comes from Latin "ferrum" meaning iron. Mnemonic: "Fe" sounds like "ferr" in "ferrous."',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'How many bones are in the adult human body?',
        options: ['186', '206', '226', '256'],
        correctAnswer: '206',
        topic: 'science-memory',
        explanation: 'An adult has 206 bones. Babies have about 270 that fuse as they grow. See it as: 20 + 6 = 206.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'In what year was the United Nations founded?',
        options: ['1945', '1950', '1939', '1948'],
        correctAnswer: '1945',
        topic: 'history-memory',
        explanation: 'The UN was founded after WWII in 1945. Memory aid: 1945 = end of WWII = start of the UN.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What is the chemical symbol for water?',
        correctAnswer: 'H2O',
        topic: 'science-memory',
        explanation: 'Water is H₂O: 2 hydrogen atoms bonded to 1 oxygen atom. The 2 in H₂O reminds you there are 2 hydrogens.',
        interactionType: 'text-input',
      },
      {
        questionText: 'Which ocean is the largest?',
        options: ['Pacific', 'Atlantic', 'Indian', 'Arctic'],
        correctAnswer: 'Pacific',
        topic: 'geography-memory',
        explanation: 'The Pacific Ocean is the largest and deepest ocean, covering about 63 million square miles.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Type the name of the longest river in the world:',
        correctAnswer: 'Nile',
        topic: 'geography-memory',
        explanation: 'The Nile River is about 6,650 km (4,130 miles) long, flowing through 11 countries in Africa.',
        interactionType: 'text-input',
      },
      {
        questionText: 'What is the speed of light approximately?',
        options: ['300,000 km/s', '150,000 km/s', '500,000 km/s', '100,000 km/s'],
        correctAnswer: '300,000 km/s',
        topic: 'science-memory',
        explanation: 'Light travels at about 300,000 km/s (exactly 299,792 km/s). It can circle Earth 7.5 times in one second!',
        interactionType: 'multiple-choice',
      },
    ],
  },

  // ─── 5. Logic Puzzles ────────────────────────────────────────
  {
    name: 'Logic Puzzles',
    description: 'Master deductive reasoning and critical thinking. Each puzzle teaches you how to think, not what to think.',
    enhances: 'Critical Thinking, Deduction, Problem Solving',
    example: 'If all A are B, and some B are C, can we conclude some A are C?',
    type: 'cognitive',
    difficulty: 'medium',
    topic: 'logic',
    questionBank: [
      {
        questionText: 'All cats are mammals. Some mammals are pets. Which conclusion is valid?',
        options: ['All cats are pets', 'Some cats are pets', 'All pets are cats', 'None can be concluded'],
        correctAnswer: 'None can be concluded',
        topic: 'deductive-reasoning',
        explanation: 'This is a classic logic trap. All cats are in the "mammals" set, and some mammals are in the "pets" set — but we don\'t know if any of those pet-mammals are cats. Never assume something is true without evidence.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'If it is raining, the ground is wet. The ground is wet. What can you conclude?',
        options: ['It is raining', 'It is not raining', 'It might be raining or another cause', 'The ground is dry'],
        correctAnswer: 'It might be raining or another cause',
        topic: 'conditional-logic',
        explanation: 'This is "affirming the consequent" — a logical fallacy. Rain causes wet ground, but wet ground could also be from a sprinkler, spilled water, etc. You cannot conclude the cause from the effect alone.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'A is taller than B. B is taller than C. Who is the shortest?',
        options: ['A', 'B', 'C', 'Cannot determine'],
        correctAnswer: 'C',
        topic: 'ordering-logic',
        explanation: 'If A > B and B > C, then A > B > C. So C is the shortest. This is a transitive relationship.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'If all squares are rectangles, and some rectangles are red, what must be true?',
        options: ['All squares are red', 'Some squares are red', 'All red shapes are rectangles', 'None must be true'],
        correctAnswer: 'None must be true',
        topic: 'deductive-reasoning',
        explanation: 'All squares are in the "rectangles" set. Some rectangles are red, but we don\'t know if any of them are the square subset. You can\'t conclude anything about squares from "some rectangles."',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Five people in a race: Alice finishes before Bob. Charlie finishes after Bob but before Dana. Eve finishes last. Who finishes first?',
        options: ['Alice', 'Bob', 'Charlie', 'Dana'],
        correctAnswer: 'Alice',
        topic: 'ordering-logic',
        explanation: 'Step by step: Alice > Bob, Bob > Charlie > Dana (Charlie before Dana), Eve last. Order: Alice → Bob → Charlie → Dana → Eve.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'A bat and a ball cost $1.10 in total. The bat costs $1.00 more than the ball. How much does the ball cost?',
        options: ['$0.05', '$0.10', '$0.15', '$0.01'],
        correctAnswer: '$0.05',
        topic: 'lateral-thinking',
        explanation: 'Most people say $0.10, but that would make the bat $1.00 (only $0.90 more). If ball = $0.05, bat = $1.05 (exactly $1.00 more). Total: $1.10. Always double-check your gut instinct in logic problems.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'If today is Tuesday, what day will it be in 100 days?',
        options: ['Thursday', 'Wednesday', 'Friday', 'Monday'],
        correctAnswer: 'Thursday',
        topic: 'modular-arithmetic',
        explanation: 'Every 7 days it\'s Tuesday again. 100 ÷ 7 = 14 weeks and 2 days remainder. Tuesday + 2 = Thursday.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'You see a house with all four windows facing south. A bear walks by. What color is the bear?',
        options: ['White', 'Brown', 'Black', 'Red'],
        correctAnswer: 'White',
        topic: 'lateral-thinking',
        explanation: 'If all windows face south, the house is at the North Pole. The only bear at the North Pole is a polar bear, which is white. This tests your ability to think about implications, not just stated facts.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'I am an odd number. Take away a letter and I become even. What number am I?',
        options: ['Seven', 'Nine', 'Three', 'Five'],
        correctAnswer: 'Seven',
        topic: 'word-logic',
        explanation: 'Take away the "s" from "seven" and you get "even." This is a wordplay puzzle — the answer is hidden in the spelling, not the math.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'If you divide 30 by 1/2 and add 10, what do you get?',
        options: ['70', '25', '45', '55'],
        correctAnswer: '70',
        topic: 'lateral-thinking',
        explanation: '30 ÷ (1/2) = 30 × 2 = 60. Then 60 + 10 = 70. People often mistakenly do 30 ÷ 2 = 15 + 10 = 25. The trick is dividing by half (which means multiply by 2), not dividing in half.',
        interactionType: 'multiple-choice',
      },
    ],
  },

  // ─── 6. Word Association ─────────────────────────────────────
  {
    name: 'Word Association',
    description: 'Build mental connections between words to enhance verbal fluency, analogical thinking, and creative associations.',
    enhances: 'Creativity, Verbal Fluency, Associative Thinking',
    example: 'What word connects "ocean", "wave", and "tide"?',
    type: 'vocabulary',
    difficulty: 'medium',
    topic: 'vocabulary',
    questionBank: [
      {
        questionText: 'Which is most closely associated with "astronomy"?',
        options: ['Telescope', 'Microscope', 'Stethoscope', 'Periscope'],
        correctAnswer: 'Telescope',
        topic: 'word-connections',
        explanation: 'All "-scope" words are viewing instruments. A telescope (from Greek "tele" = far) is used to view distant stars — hence it belongs with astronomy.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What is an antonym of "benevolent"?',
        options: ['Malevolent', 'Benevolent', 'Excellent', 'Violent'],
        correctAnswer: 'Malevolent',
        topic: 'antonyms',
        explanation: '"Bene-" means good (Latin). "Male-" means bad/evil. So benevolent = good-wishing, malevolent = evil-wishing, making them direct antonyms.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Complete the analogy: Book is to Chapter as Tree is to ___',
        options: ['Leaf', 'Branch', 'Root', 'Forest'],
        correctAnswer: 'Branch',
        topic: 'analogies',
        explanation: 'A chapter is a section of a book, just as a branch is a section of a tree. Both are part-whole relationships but not the smallest part — leaves are to trees as words are to chapters.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Which word does NOT belong with the others?',
        options: ['Guitar', 'Piano', 'Flute', 'Sculpture'],
        correctAnswer: 'Sculpture',
        topic: 'categorization',
        explanation: 'Guitar, piano, and flute are all musical instruments. Sculpture is a visual art form, not an instrument.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What do "photosynthesis", "chlorophyll", and "sunlight" all relate to?',
        options: ['Plants', 'Animals', 'Weather', 'Oceans'],
        correctAnswer: 'Plants',
        topic: 'thematic-links',
        explanation: 'All three are connected to how plants produce food: chlorophyll (the green pigment) captures sunlight to drive photosynthesis (the process of converting light to energy).',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What do you call a word that sounds like its meaning? (e.g., buzz, click)',
        correctAnswer: 'onomatopoeia',
        topic: 'word-types',
        explanation: 'Onomatopoeia is the formation of a word from a sound associated with what it\'s named. Buzz, click, boom, splash — the word sounds like the thing it describes.',
        interactionType: 'text-input',
      },
      {
        questionText: 'Which prefix means "against" or "opposite"?',
        options: ['Anti-', 'Pre-', 'Co-', 'Mis-'],
        correctAnswer: 'Anti-',
        topic: 'prefixes',
        explanation: '"Anti-" from Greek means against or opposite. Examples: antibiotic (against bacteria), antisocial (opposite of social), antidote (works against poison).',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Complete the analogy: Puppy is to Dog as Kitten is to ___',
        options: ['Cat', 'Kitty', 'Feline', 'Animal'],
        correctAnswer: 'Cat',
        topic: 'analogies',
        explanation: 'A puppy is a young dog, just as a kitten is a young cat. The relationship is "young form of."',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What does the suffix "-ology" mean?',
        options: ['The study of', 'Fear of', 'Like or similar to', 'Without'],
        correctAnswer: 'The study of',
        topic: 'suffixes',
        explanation: '"-ology" comes from Greek "logos" (word/reason). Biology = study of life, Psychology = study of mind, Geology = study of Earth.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Type a word that means "to make something appear larger than it is":',
        correctAnswer: 'exaggerate',
        topic: 'word-meanings',
        explanation: 'To exaggerate means to represent something as larger, greater, more important than it actually is. From Latin "exaggerare" = to heap up.',
        interactionType: 'text-input',
      },
    ],
  },

  // ─── 7. Spatial Reasoning ────────────────────────────────────
  {
    name: 'Spatial Reasoning',
    description: 'Develop your ability to visualize, rotate, and manipulate objects in your mind. Essential for engineering, design, and navigation.',
    enhances: 'Visualization, Mental Rotation, Navigation',
    example: 'If you fold this net, what 3D shape do you get?',
    type: 'cognitive',
    difficulty: 'medium',
    topic: 'spatial',
    questionBank: [
      {
        questionText: 'How many faces does a cube have?',
        options: ['6', '4', '8', '12'],
        correctAnswer: '6',
        topic: '3d-shapes',
        explanation: 'A cube has 6 faces (top, bottom, front, back, left, right), 8 vertices (corners), and 12 edges.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'If you look at a cube from one corner, what shape do you see?',
        options: ['Hexagon', 'Square', 'Triangle', 'Pentagon'],
        correctAnswer: 'Hexagon',
        topic: 'visual-projection',
        explanation: 'When viewing a cube from a corner (not face-on), the visible faces form a hexagonal outline. This is because 3 faces are visible, each contributing 2 edges to the silhouette.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What 3D shape has no edges or vertices?',
        options: ['Sphere', 'Cylinder', 'Cone', 'Pyramid'],
        correctAnswer: 'Sphere',
        topic: '3d-shapes',
        explanation: 'A sphere is perfectly round with no edges, no vertices, and one continuous curved surface. Every point on its surface is the same distance from its center.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'How many edges does a square pyramid have? (a pyramid with a square base)',
        options: ['8', '5', '10', '6'],
        correctAnswer: '8',
        topic: '3d-shapes',
        explanation: 'A square pyramid has: 4 edges around the base, plus 4 edges from each base corner to the apex. Total = 8 edges.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'If you cut a cone horizontally, what shape is the cross-section?',
        options: ['Circle', 'Triangle', 'Square', 'Rectangle'],
        correctAnswer: 'Circle',
        topic: 'cross-sections',
        explanation: 'A horizontal (parallel to base) cut through a cone always produces a circle. The circle gets smaller as you cut closer to the tip.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Which net can be folded to make a cube? (Select the correct description)',
        options: ['A cross of 6 squares', '4 squares in a row', '5 squares in an L-shape', '7 squares in a line'],
        correctAnswer: 'A cross of 6 squares',
        topic: 'nets',
        explanation: 'A cube has 6 faces. The "cross" pattern (a central square with 4 around it and 1 attached to one of those 4) folds into a cube without any overlapping faces.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'If you rotate a square 90 degrees, what shape do you get?',
        options: ['Same square', 'Rectangle', 'Diamond', 'Rhombus'],
        correctAnswer: 'Same square',
        topic: 'rotation',
        explanation: 'A square rotated 90 degrees still looks identical because all sides are equal and all angles are 90°. This is called rotational symmetry.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What is the minimum number of colors needed to color any map so no adjacent regions share the same color?',
        options: ['4', '3', '5', '2'],
        correctAnswer: '4',
        topic: 'visual-logic',
        explanation: 'The Four Color Theorem states that 4 colors are always sufficient to color any map such that no adjacent regions have the same color. This was the first major theorem proven by computer.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Arrange these shapes from FEWEST to MOST sides: Triangle, Square, Pentagon, Hexagon',
        puzzleType: 'sequence-order',
        items: ['Triangle', 'Square', 'Pentagon', 'Hexagon'],
        correctAnswer: 'Triangle,Square,Pentagon,Hexagon',
        topic: '3d-shapes',
        explanation: 'Triangle has 3 sides, Square has 4, Pentagon has 5, Hexagon has 6. Arranged by increasing number of sides.',
        interactionType: 'puzzle',
      },
      {
        questionText: 'Arrange in order of INCREASING symmetry: Arrow, Square, Circle',
        puzzleType: 'sequence-order',
        items: ['Arrow (1 line)', 'Square (4 lines)', 'Circle (infinite lines)'],
        correctAnswer: 'Arrow (1 line),Square (4 lines),Circle (infinite lines)',
        topic: 'rotation',
        explanation: 'An arrow has 1 line of symmetry, a square has 4, and a circle has infinite lines of symmetry through its center.',
        interactionType: 'puzzle',
      },
    ],
  },

  // ─── 8. Quick Reflexes ────────────────────────────────────────
  {
    name: 'Quick Reflexes',
    description: 'Build mental processing speed through rapid categorization, odd-one-out detection, and timed pattern matching.',
    enhances: 'Processing Speed, Reaction Time, Decision Making',
    example: 'Which one is different?',
    type: 'cognitive',
    difficulty: 'easy',
    topic: 'reflexes',
    questionBank: [
      {
        questionText: 'Which one does NOT belong? Apple, Banana, Carrot, Grape',
        options: ['Apple', 'Banana', 'Carrot', 'Grape'],
        correctAnswer: 'Carrot',
        topic: 'quick-categorization',
        explanation: 'Apple, banana, and grape are fruits. Carrot is a vegetable. The odd one out is based on category.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Which is the smallest? Mountain, Hill, Mound, Valley',
        options: ['Mountain', 'Hill', 'Mound', 'Valley'],
        correctAnswer: 'Mound',
        topic: 'quick-comparison',
        explanation: 'Ordered by size: Mountain > Hill > Mound > Valley (valley is a dip, not a height). Among heights, mound is smallest.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Which word has the most syllables?',
        options: ['Unbelievable', 'Cat', 'Running', 'Jump'],
        correctAnswer: 'Unbelievable',
        topic: 'quick-categorization',
        explanation: 'Un-be-liev-a-ble = 5 syllables. Cat = 1, Run-ning = 2, Jump = 1.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Which is the correct order from smallest to largest?',
        options: ['cm, m, km', 'm, cm, km', 'km, m, cm', 'cm, km, m'],
        correctAnswer: 'cm, m, km',
        topic: 'quick-ordering',
        explanation: 'cm (centimeter) = 1/100 of a meter. m (meter) = base unit. km (kilometer) = 1000 meters.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Which of these is a prime number?',
        options: ['17', '15', '21', '27'],
        correctAnswer: '17',
        topic: 'quick-identification',
        explanation: 'A prime number has exactly 2 factors: 1 and itself. 17 is prime. 15=3×5, 21=3×7, 27=3×9.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Which animal is a mammal?',
        options: ['Dolphin', 'Shark', 'Crocodile', 'Eagle'],
        correctAnswer: 'Dolphin',
        topic: 'quick-categorization',
        explanation: 'Dolphins are mammals — they breathe air, give birth to live young, and nurse their babies. Despite living in water, they\'re not fish.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What comes next in the alphabet after "Z"? (Think carefully)',
        correctAnswer: 'A',
        topic: 'lateral-thinking-reflexes',
        explanation: 'The alphabet is cyclical: after Z comes A. Or in terms of opposite: Z\'s opposite in some puzzles is A. The key is to think about patterns, not just memorization.',
        interactionType: 'text-input',
      },
      {
        questionText: 'Which word is the odd one out? Hammer, Screwdriver, Nail, Wrench',
        options: ['Hammer', 'Screwdriver', 'Nail', 'Wrench'],
        correctAnswer: 'Nail',
        topic: 'quick-categorization',
        explanation: 'Hammer, screwdriver, and wrench are tools. A nail is a fastener, not a tool used to drive it. Quick categorization means spotting the functional difference.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Spot the odd color: Red, Blue, Green, Square',
        options: ['Red', 'Blue', 'Green', 'Square'],
        correctAnswer: 'Square',
        topic: 'quick-categorization',
        explanation: 'Red, blue, and green are colors. Square is a shape. This tests your ability to rapidly identify category mismatches.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Arrange from SHORTEST to LONGEST duration: Second, Minute, Hour, Day',
        puzzleType: 'sequence-order',
        items: ['Second', 'Minute', 'Hour', 'Day'],
        correctAnswer: 'Second,Minute,Hour,Day',
        topic: 'quick-ordering',
        explanation: '60 seconds = 1 minute, 60 minutes = 1 hour, 24 hours = 1 day. Ordered by increasing duration.',
        interactionType: 'puzzle',
      },
    ],
  },

  // ─── 9. Creative Thinking ────────────────────────────────────
  {
    name: 'Creative Thinking',
    description: 'Unlock your imagination with exercises that push you to think beyond conventional boundaries and make novel connections.',
    enhances: 'Creativity, Innovation, Divergent Thinking',
    example: 'How many uses can you think of for a paperclip?',
    type: 'cognitive',
    difficulty: 'hard',
    topic: 'creativity',
    questionBank: [
      {
        questionText: 'What is the "balloon problem"? A candle, tacks, and a box of matches — how do you attach the candle to the wall so it burns safely?',
        options: ['Tack the box to the wall as a shelf', 'Melt wax and stick candle', 'Hold candle with tacks', 'Light matches to heat the tacks'],
        correctAnswer: 'Tack the box to the wall as a shelf',
        topic: 'functional-fixedness',
        explanation: 'The classic insight: people see the box as "container for tacks" but it can also be "a platform." Empty the box, tack it to the wall, place the candle on it. This shows how breaking mental assumptions leads to creative solutions.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What connects these three words: "time", "fly", "like"? (Think of a common phrase)',
        options: ['an arrow', 'a bird', 'the wind', 'a dream'],
        correctAnswer: 'an arrow',
        topic: 'divergent-thinking',
        explanation: '"Time flies like an arrow" — but also "time" could be the subject and "flies" the verb! This ambiguity is the basis for the famous quote: "Time flies like an arrow; fruit flies like a banana."',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'If you have a 3-gallon jug and a 5-gallon jug, how can you measure exactly 4 gallons?',
        options: ['Fill 5, pour to 3, empty 3, pour remaining 2 to 3, fill 5, pour to 3', 'Fill 3 twice', 'Fill 5 and 3 together', 'Fill 3, pour to 5, fill 3 again'],
        correctAnswer: 'Fill 5, pour to 3, empty 3, pour remaining 2 to 3, fill 5, pour to 3',
        topic: 'problem-solving',
        explanation: 'Step by step: 1) Fill 5. 2) Pour 5→3 (3 is now full, 5 has 2 left). 3) Empty 3. 4) Pour the 2 from 5→3 (3 now has 2). 5) Fill 5. 6) Pour 5→3 (3 had 2, needs 1 more to fill, so 5 loses 1). 7) 5 now has exactly 4 gallons!',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Which shape has infinite lines of symmetry?',
        options: ['Circle', 'Square', 'Triangle', 'Pentagon'],
        correctAnswer: 'Circle',
        topic: 'creative-visualization',
        explanation: 'A circle has infinite lines of symmetry — you can fold it in half through any line passing through its center. A square has 4, a triangle has up to 3, a pentagon has 5.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What do you call a question that has no answer but makes you think?',
        correctAnswer: 'rhetorical',
        topic: 'creative-language',
        explanation: 'A rhetorical question is asked to make a point rather than to get an answer. From Greek "rhetor" (orator/speaker). Examples: "Is the Pope Catholic?" or "Why are we here?"',
        interactionType: 'text-input',
      },
      {
        questionText: 'If a rooster lays an egg on top of a barn, which way does it roll?',
        options: ['Roosters don\'t lay eggs', 'Down the left side', 'Down the right side', 'It doesn\'t roll'],
        correctAnswer: 'Roosters don\'t lay eggs',
        topic: 'lateral-creativity',
        explanation: 'Only hens (female chickens) lay eggs. Roosters are male. The question tricks you into visualizing the barn while missing the fundamental impossibility in the premise.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Investigate the clues to figure out: What gets wetter the more it dries?',
        clues: [
          { label: '🧩 Clue 1', content: 'You use it every day.' },
          { label: '🧩 Clue 2', content: 'It is found in every bathroom.' },
          { label: '🧩 Clue 3', content: 'It is made of cloth or fabric.' },
          { label: '🧩 Clue 4', content: 'Its job is to absorb water.' },
        ],
        correctAnswer: 'towel',
        topic: 'lateral-creativity',
        explanation: 'A towel! The paradox works because a towel "dries" you by getting wet itself. The more it dries things, the wetter it becomes.',
        interactionType: 'hover-reveal',
      },
      {
        questionText: 'Hover the clues to investigate: What has keys but can\'t open locks?',
        clues: [
          { label: '🎹 Clue 1', content: 'It has many keys.' },
          { label: '🎹 Clue 2', content: 'It makes beautiful sounds.' },
          { label: '🎹 Clue 3', content: 'It has black and white parts.' },
          { label: '🎹 Clue 4', content: 'Musicians press its keys to create music.' },
        ],
        correctAnswer: 'piano',
        topic: 'creative-visualization',
        explanation: 'A piano has keys (the black and white ones you press), but they\'re musical keys, not door keys. This is a classic riddle that plays on the double meaning of "key."',
        interactionType: 'hover-reveal',
      },
      {
        questionText: 'A brick is used to build walls. What else could it be used for? This tests:',
        options: ['Divergent thinking', 'Memory recall', 'Pattern recognition', 'Language skills'],
        correctAnswer: 'Divergent thinking',
        topic: 'divergent-thinking',
        explanation: 'Divergent thinking means generating many creative solutions beyond the obvious use. A brick could be a paperweight, a doorstop, a tool for making music, or even a piece of art. This is a core creative thinking skill.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Complete the creative analogy: "Water is to ice as thought is to ___"',
        correctAnswer: 'action',
        topic: 'creative-language',
        explanation: 'Water becomes solid as ice; thoughts become real as actions. Creative analogies work by finding the deep relationship, not just surface similarities.',
        interactionType: 'text-input',
      },
    ],
  },

  // ─── 10. Emotional Intelligence ──────────────────────────────
  {
    name: 'Emotional Intelligence',
    description: 'Understand emotions — yours and others\' — through scenarios that build empathy, self-awareness, and social skills.',
    enhances: 'Empathy, Self-Awareness, Communication',
    example: 'A friend is unusually quiet. What might they be feeling?',
    type: 'cognitive',
    difficulty: 'hard',
    topic: 'eq',
    questionBank: [
      {
        questionText: 'A colleague says "fine" but their arms are crossed and they won\'t look at you. What\'s most likely happening?',
        options: ['They are upset', 'They are cold', 'They are thinking', 'They are relaxed'],
        correctAnswer: 'They are upset',
        topic: 'reading-others',
        explanation: 'Body language often contradicts words. Crossed arms and avoiding eye contact suggest defensiveness or distress. Emotional intelligence means noticing and addressing the mismatch between words and body language.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Someone shares a problem with you. The best first response is:',
        options: ['Listen without interrupting', 'Give immediate advice', 'Share your own similar story', 'Tell them it will be fine'],
        correctAnswer: 'Listen without interrupting',
        topic: 'active-listening',
        explanation: 'Most people don\'t need advice — they need to feel heard. Listening without interrupting validates their feelings and helps them process. Advice comes later, if at all.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'You receive critical feedback. The emotionally intelligent response is:',
        options: ['Thank them and reflect on it', 'Defend your actions', 'Ignore it completely', 'Criticize them back'],
        correctAnswer: 'Thank them and reflect on it',
        topic: 'self-awareness',
        explanation: 'Emotional intelligence means separating your self-worth from your actions. Thanking feedback givers keeps communication open and helps you grow, even if the feedback stings at first.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What is "empathy"?',
        options: ['Understanding others\' feelings', 'Feeling sorry for someone', 'Agreeing with everyone', 'Controlling your emotions'],
        correctAnswer: 'Understanding others\' feelings',
        topic: 'empathy',
        explanation: 'Empathy is the ability to understand and share the feelings of another. It\'s different from sympathy (feeling compassion) or pity (feeling sorry for someone). Empathy says "I see you and I\'m with you."',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'A team member made a mistake. The most constructive approach is:',
        options: ['What can we learn from this?', 'Who made this mistake?', 'This shouldn\'t have happened', 'Fix it immediately'],
        correctAnswer: 'What can we learn from this?',
        topic: 'conflict-resolution',
        explanation: '"What can we learn?" turns blame into growth. It assumes the mistake happened, focuses on improvement, and preserves the person\'s dignity — all key elements of emotional intelligence in leadership.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What does it mean to "regulate" your emotions?',
        correctAnswer: 'manage',
        topic: 'self-regulation',
        explanation: 'Emotion regulation means managing your emotional responses — not suppressing them, but choosing how to express them. It\'s a skill that can be learned and improved with practice.',
        interactionType: 'text-input',
      },
      {
        questionText: 'Two people are in an argument about whose turn it is to do dishes. The best approach is:',
        options: ['Suggest a fair schedule', 'Just do it yourself', 'Argue back', 'Ignore the dishes'],
        correctAnswer: 'Suggest a fair schedule',
        topic: 'conflict-resolution',
        explanation: 'A fair schedule addresses the root problem (no clear system) rather than winning the argument. This is an example of moving from positional bargaining to collaborative problem-solving.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What is "cognitive reappraisal"?',
        options: ['Changing how you think about a situation', 'Forgetting negative events', 'Agreeing with everyone', 'Suppressing emotions'],
        correctAnswer: 'Changing how you think about a situation',
        topic: 'self-regulation',
        explanation: 'Cognitive reappraisal means reframing how you interpret a situation. For example, seeing a job rejection as "redirection" rather than "failure." It is one of the most effective emotion regulation strategies.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'A friend just lost their job. The most empathetic response is:',
        options: ['"That must be really hard. I\'m here for you."', '"You\'ll find something better."', '"I know someone who got laid off too."', '"The job market is tough right now."'],
        correctAnswer: '"That must be really hard. I\'m here for you."',
        topic: 'empathy',
        explanation: 'Empathy validates the other person\'s feelings without minimizing, comparing, or problem-solving. Statements like "That must be really hard" show you understand their emotional state.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What does "emotional granularity" mean?',
        options: ['Naming specific emotions precisely', 'Having very strong emotions', 'Hiding your emotions well', 'Feeling many emotions at once'],
        correctAnswer: 'Naming specific emotions precisely',
        topic: 'self-awareness',
        explanation: 'Emotional granularity is the ability to identify and label your emotions with precision — e.g., distinguishing "disappointed" from "frustrated." Higher granularity leads to better emotional regulation and well-being.',
        interactionType: 'multiple-choice',
      },
    ],
  },

  // ─── 11. Data Interpretation ─────────────────────────────────
  {
    name: 'Data Interpretation',
    description: 'Learn to read charts, tables, and graphs. Extract meaningful insights from numbers and make data-driven decisions.',
    enhances: 'Analytical Thinking, Statistical Literacy, Decision Making',
    example: 'If a bar chart shows sales increasing every month, what trend is it showing?',
    type: 'cognitive',
    difficulty: 'hard',
    topic: 'data',
    questionBank: [
      {
        questionText: 'If 60% of students passed a test and there were 200 students, how many passed?',
        options: ['120', '80', '140', '100'],
        correctAnswer: '120',
        topic: 'percentage-calculation',
        explanation: '60% of 200 = 0.6 × 200 = 120 students. Tip: 60% is the same as 60/100 = 3/5. 3/5 of 200 = (200÷5)×3 = 40×3 = 120.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'The average of 4 numbers is 15. Three numbers are 12, 18, and 15. What is the fourth number?',
        options: ['15', '16', '14', '17'],
        correctAnswer: '15',
        topic: 'averages',
        explanation: 'Sum = average × count = 15 × 4 = 60. Known sum = 12+18+15 = 45. Fourth = 60 - 45 = 15.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'A shirt costs $40 and is on 25% off. What is the sale price?',
        options: ['$30', '$35', '$25', '$32'],
        correctAnswer: '$30',
        topic: 'discounts',
        explanation: '25% off means you pay 75%. 75% of $40 = 0.75 × 40 = $30. Alternate: 25% = $10 off, so $40 - $10 = $30.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'If a population grows from 1,000 to 1,200, what is the percentage increase?',
        options: ['20%', '15%', '25%', '10%'],
        correctAnswer: '20%',
        topic: 'growth-rate',
        explanation: 'Increase = 1200 - 1000 = 200. Percentage increase = (increase/original) × 100 = 200/1000 × 100 = 20%.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'A data set has values: 3, 7, 7, 7, 9, 10, 12. What is the median?',
        options: ['7', '8', '9', '10'],
        correctAnswer: '7',
        topic: 'median',
        explanation: 'The median is the middle value when sorted. With 7 numbers, the 4th is the median: 3, 7, 7, 7, 9, 10, 12. The middle number is 7.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'A data set has values: 2, 4, 6, 8, 10. What is the range?',
        options: ['8', '6', '10', '4'],
        correctAnswer: '8',
        topic: 'averages',
        explanation: 'The range is the difference between the largest and smallest values: 10 - 2 = 8. Range tells you how spread out the data is.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'A survey shows 70% of people prefer coffee over tea. If 500 people were surveyed, how many prefer tea?',
        options: ['150', '350', '100', '200'],
        correctAnswer: '150',
        topic: 'percentage-calculation',
        explanation: 'If 70% prefer coffee, then 30% prefer tea. 30% of 500 = 0.3 × 500 = 150 people. Always find the complement percentage first.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'In a pie chart, one category takes up 90 degrees. What percentage does it represent?',
        options: ['25%', '30%', '15%', '20%'],
        correctAnswer: '25%',
        topic: 'percentage-calculation',
        explanation: 'A full circle is 360 degrees. 90/360 = 1/4 = 25%. A pie chart section\'s angle ÷ 360 × 100 gives the percentage.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'A company\'s revenue was $1M in 2023 and $1.5M in 2024. What was the growth rate?',
        options: ['50%', '33%', '25%', '40%'],
        correctAnswer: '50%',
        topic: 'percentage-calculation',
        explanation: 'Growth rate = (new - old) / old × 100 = (1.5M - 1M) / 1M × 100 = 0.5 × 100 = 50%. Always divide by the original, not the new value.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'A survey asked 100 people about their favorite color: 40 chose blue, 30 red, 20 green, and 10 yellow. What percentage chose blue?',
        options: ['40%', '30%', '20%', '10%'],
        correctAnswer: '40%',
        topic: 'percentage-calculation',
        explanation: '40 out of 100 people chose blue. 40/100 = 40%. When the total is exactly 100, the percentage is simply the count.',
        interactionType: 'multiple-choice',
      },
    ],
  },

  // ─── 12. Language Learning ────────────────────────────────────
  {
    name: 'Language Learning',
    description: 'Explore how languages work — grammar patterns, word origins, and the fascinating connections between different languages.',
    enhances: 'Linguistic Awareness, Memory, Pattern Recognition',
    example: 'What language family does English belong to?',
    type: 'vocabulary',
    difficulty: 'hard',
    topic: 'language',
    questionBank: [
      {
        questionText: 'Which language family does English belong to?',
        options: ['Germanic', 'Romance', 'Slavic', 'Arabic'],
        correctAnswer: 'Germanic',
        topic: 'language-families',
        explanation: 'English is a West Germanic language. Words like "house" (German: Haus), "water" (Wasser), and "mother" (Mutter) share Germanic roots. The Romance influence came later via French.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What is the grammatical term for a word that modifies a noun?',
        options: ['Adjective', 'Adverb', 'Verb', 'Pronoun'],
        correctAnswer: 'Adjective',
        topic: 'grammar',
        explanation: 'Adjectives modify (describe) nouns. "Red" car, "tall" building, "happy" child. Adverbs modify verbs, adjectives, or other adverbs.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Which language has the most native speakers worldwide?',
        options: ['Mandarin Chinese', 'English', 'Spanish', 'Hindi'],
        correctAnswer: 'Mandarin Chinese',
        topic: 'language-facts',
        explanation: 'Mandarin Chinese has about 920 million native speakers, followed by Spanish (480M) and English (380M). However, English has the most total speakers including second-language learners.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What is a "portmanteau" word?',
        options: ['Blended words', 'Opposite words', 'Borrowed words', 'Ancient words'],
        correctAnswer: 'Blended words',
        topic: 'word-formation',
        explanation: 'A portmanteau blends two words: "brunch" (breakfast + lunch), "smog" (smoke + fog), "motel" (motor + hotel). From French "portmanteau" meaning a suitcase that opens into two parts.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Which writing system is the oldest still in use?',
        options: ['Chinese characters', 'Latin alphabet', 'Arabic script', 'Devanagari'],
        correctAnswer: 'Chinese characters',
        topic: 'writing-systems',
        explanation: 'Chinese characters (Hanzi) have been in continuous use for over 3,000 years, making them the oldest writing system still actively used today.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What do you call a word taken from one language and used in another?',
        options: ['Loanword', 'Root word', 'Compound word', 'Base word'],
        correctAnswer: 'Loanword',
        topic: 'language-facts',
        explanation: 'A loanword (or borrowing) is a word adopted from one language into another. Examples: "sushi" (Japanese→English), "kindergarten" (German→English), "algebra" (Arabic→English).',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'How many grammatical cases does German use for nouns?',
        options: ['4', '3', '5', '6'],
        correctAnswer: '4',
        topic: 'grammar',
        explanation: 'German has 4 cases: Nominative (subject), Accusative (direct object), Dative (indirect object), and Genitive (possessive). Cases show the function of a noun in a sentence.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What term describes two languages used in the same region by different groups?',
        options: ['Diglossia', 'Dialect', 'Creole', 'Idiolect'],
        correctAnswer: 'Diglossia',
        topic: 'language-families',
        explanation: 'Diglossia is when two languages (or two varieties of the same language) are used in a community but for different purposes — one "high" formal variety and one "low" everyday variety. Example: Standard Arabic (formal) and local Arabic dialects (daily use).',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What is the "Sapir-Whorf hypothesis"?',
        options: ['Language shapes how we think', 'All languages have the same grammar', 'Language is innate', 'Animals can learn language'],
        correctAnswer: 'Language shapes how we think',
        topic: 'language-facts',
        explanation: 'The Sapir-Whorf hypothesis proposes that the language you speak influences how you perceive and think about the world. For example, languages with different color terms may affect how speakers perceive color differences.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Match these Romance languages to their countries: French, Spanish, Italian, Portuguese',
        puzzleType: 'sequence-order',
        items: ['French → France', 'Spanish → Spain', 'Italian → Italy', 'Portuguese → Portugal'],
        correctAnswer: 'French → France,Spanish → Spain,Italian → Italy,Portuguese → Portugal',
        topic: 'language-families',
        explanation: 'Romance languages all evolved from Latin (the language of the Roman Empire). French, Spanish, Italian, and Portuguese each became the dominant language of their respective countries.',
        interactionType: 'puzzle',
      },
    ],
  },

  // ─── 13. Attention & Focus ──────────────────────────────────
  {
    name: 'Attention & Focus',
    description: 'Build your ability to concentrate, ignore distractions, and sustain mental effort over time — a foundational cognitive skill.',
    enhances: 'Concentration, Focus, Mental Stamina',
    example: 'Which letter appears most frequently in this sentence?',
    type: 'cognitive',
    difficulty: 'easy',
    topic: 'attention',
    questionBank: [
      {
        questionText: 'How many times does the letter "e" appear in this sentence: "The best time to plant a tree was twenty years ago."',
        options: ['8', '6', '10', '7'],
        correctAnswer: '8',
        topic: 'sustained-attention',
        explanation: 'Count carefully: The(1) best(2) time(3) to(4) plant(5) a(6) tree(7,8) was twenty years ago. There are 8 letter "e"s in total. This tests sustained focused attention.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What number should replace the question mark? 1, 1, 2, 3, 5, 8, 13, ?',
        options: ['21', '20', '18', '24'],
        correctAnswer: '21',
        topic: 'sustained-attention',
        explanation: 'This is the Fibonacci sequence where each number is the sum of the two before it. 8 + 13 = 21. Recognizing this pattern requires continuous focus through the sequence.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Count backwards from 100 by 7. After 100, 93, 86, what comes next?',
        options: ['79', '80', '78', '81'],
        correctAnswer: '79',
        topic: 'sustained-attention',
        explanation: '86 - 7 = 79. Serial subtraction tests sustained attention and working memory. This is a classic cognitive assessment task.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Spot the difference: "Their" vs "There" — which sentence uses the correct word?',
        options: ['"Their going to the store"', '"There going to the store"', '"They\'re going to the store"', '"Their is a cat outside"'],
        correctAnswer: '"They\'re going to the store"',
        topic: 'selective-attention',
        explanation: '"They\'re" = "they are," which is correct here. "Their" shows possession, "there" shows location. This tests selective attention to detail in commonly confused words.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'How many F\'s are in this sentence: "Fresh fried fish for Friday"',
        options: ['4', '3', '5', '6'],
        correctAnswer: '4',
        topic: 'sustained-attention',
        explanation: 'F-resH(no), F-ried(yes), F-ish(yes), F-or(yes), F-riday(yes). Four F\'s total. People often miss the "f" in "of" — but there is no "of" here, so it is 4.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Type the color of the text, not the word: What color is this word: "BLUE" written in red ink?',
        correctAnswer: 'red',
        topic: 'selective-attention',
        explanation: 'This is a Stroop test. The word says "BLUE" but the ink is red. The correct answer is the ink color (red), not the word. This tests your ability to override automatic reading and focus on the relevant feature.',
        interactionType: 'text-input',
      },
      {
        questionText: 'Which task pairing is an example of multitasking?',
        options: ['Walking while chewing gum', 'Reading while listening to an audiobook', 'Brewing coffee while checking emails', 'Singing while taking a shower'],
        correctAnswer: 'Reading while listening to an audiobook',
        topic: 'divided-attention',
        explanation: 'Reading and listening to an audiobook both use language processing centers, making true multitasking impossible. Your brain switches rapidly between them, reducing performance on both. The others pair automated tasks.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Type the missing number: 2, 4, 6, 8, ?, 12',
        correctAnswer: '10',
        topic: 'sustained-attention',
        explanation: 'These are even numbers increasing by 2. After 8 comes 10. Simple sequences test whether you can maintain consistent attention through the end of a task.',
        interactionType: 'text-input',
      },
      {
        questionText: 'In a room of 30 people, if everyone shakes hands with everyone exactly once, how many handshakes occur?',
        options: ['435', '870', '30', '900'],
        correctAnswer: '435',
        topic: 'sustained-attention',
        explanation: 'The formula is n(n-1)/2 = 30×29/2 = 435. Each person shakes 29 hands, but that counts each handshake twice (A-B and B-A), so divide by 2. Following multi-step reasoning requires sustained focus.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Arrange these tasks from SHORTEST to LONGEST attention span needed: Read a tweet, Watch a movie, Read a book, Write an email',
        puzzleType: 'sequence-order',
        items: ['Read a tweet', 'Write an email', 'Watch a movie', 'Read a book'],
        correctAnswer: 'Read a tweet,Write an email,Watch a movie,Read a book',
        topic: 'sustained-attention',
        explanation: 'A tweet takes seconds, an email a few minutes, a movie ~2 hours, and a book days or weeks. Different tasks require different levels of sustained attention.',
        interactionType: 'puzzle',
      },
    ],
  },

  // ─── 14. Critical Thinking & Bias ────────────────────────────
  {
    name: 'Critical Thinking & Bias',
    description: 'Learn to recognize logical fallacies, cognitive biases, and evaluate arguments with clarity and precision.',
    enhances: 'Critical Thinking, Decision Making, Argument Analysis',
    example: 'What is wrong with this argument: "Everyone believes it, so it must be true"?',
    type: 'cognitive',
    difficulty: 'medium',
    topic: 'critical-thinking',
    questionBank: [
      {
        questionText: '"Everyone I know voted for Candidate X, so Candidate X must be the most popular." This is an example of:',
        options: ['Anchoring bias', 'Selection bias', 'Confirmation bias', 'Hindsight bias'],
        correctAnswer: 'Selection bias',
        topic: 'cognitive-biases',
        explanation: 'Selection bias means drawing conclusions from a non-representative sample. Your social circle is not the whole population. The flaw is assuming your limited sample reflects everyone.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: '"If we allow same-sex marriage, next people will want to marry animals!" This argument is:',
        options: ['Slippery slope fallacy', 'Straw man fallacy', 'Ad hominem', 'Red herring'],
        correctAnswer: 'Slippery slope fallacy',
        topic: 'logical-fallacies',
        explanation: 'A slippery slope fallacy claims that taking one step will inevitably lead to extreme, undesirable consequences without evidence for that chain of events. It assumes a domino effect that is not justified.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: '"You can\'t trust his opinion on climate change because he\'s not a scientist." This could be valid if:',
        options: ['He lacks relevant expertise', 'He is biased', 'He works for a company', 'All of the above'],
        correctAnswer: 'He lacks relevant expertise',
        topic: 'argument-analysis',
        explanation: 'Questioning someone\'s expertise is valid when their claim requires specialized knowledge. But note: the ad hominem fallacy is when you attack the person instead of their argument. Distinguishing these is key.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'After a stock market crash, many people say "I knew that was going to happen." This is:',
        options: ['Hindsight bias', 'Confirmation bias', 'Overconfidence bias', 'Survivorship bias'],
        correctAnswer: 'Hindsight bias',
        topic: 'cognitive-biases',
        explanation: 'Hindsight bias is the tendency to see past events as having been predictable, even when they weren\'t. "Knew-it-all-along" phenomenon. It prevents us from learning from uncertainty.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: '"Most people who recovered from illness used this treatment, so it works." What is wrong here?',
        options: ['No control group comparison', 'Sample too small', 'Correlation is not causation', 'All of the above'],
        correctAnswer: 'No control group comparison',
        topic: 'evidence-evaluation',
        explanation: 'Without a control group (people who didn\'t use the treatment), you cannot attribute recovery to the treatment. They might have recovered naturally. This is why medical studies use randomized controlled trials.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: '"If you don\'t support this policy, you don\'t care about children." This is:',
        options: ['False dilemma', 'Ad hominem', 'Straw man', 'Appeal to emotion'],
        correctAnswer: 'False dilemma',
        topic: 'logical-fallacies',
        explanation: 'A false dilemma (or false dichotomy) presents only two extreme options when more exist. You can disagree with a specific policy and still care deeply about children. The fallacy limits the choices unfairly.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Type the name of the bias where you search for info that confirms what you already believe:',
        correctAnswer: 'confirmation bias',
        topic: 'cognitive-biases',
        explanation: 'Confirmation bias is the tendency to search for, interpret, and remember information that confirms your existing beliefs. It is one of the most pervasive biases — everyone has it, including experts.',
        interactionType: 'text-input',
      },
      {
        questionText: '"10 out of 10 dentists recommend this toothpaste!" The hidden assumption is:',
        options: ['Sample may not be representative', 'Dentists are biased', 'Toothpaste works', 'All dentists agree'],
        correctAnswer: 'Sample may not be representative',
        topic: 'evidence-evaluation',
        explanation: 'Who were those 10 dentists? They could be paid endorsers or a carefully selected group. A representative sample should be random and large enough. Always ask "who was sampled and how?"',
        interactionType: 'multiple-choice',
      },
      {
        questionText: '"The sun rose today, so it will rise tomorrow." This reasoning is:',
        options: ['Inductive reasoning', 'Deductive reasoning', 'Circular reasoning', 'Abductive reasoning'],
        correctAnswer: 'Inductive reasoning',
        topic: 'argument-analysis',
        explanation: 'Inductive reasoning generalizes from past observations to predict future ones. It is strong but not certain — the sun will rise tomorrow based on consistent past evidence. Deductive reasoning, by contrast, guarantees the conclusion if premises are true.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Investigate the clues to identify: What logical fallacy uses someone\'s lack of evidence as proof of the opposite?',
        clues: [
          { label: '📖 Clue 1', content: 'It has a Latin name.' },
          { label: '📖 Clue 2', content: 'It shifts the burden of proof.' },
          { label: '📖 Clue 3', content: 'Common example: "You can\'t prove ghosts don\'t exist, so they must exist."' },
          { label: '📖 Clue 4', content: '"Absence of evidence is not evidence of absence."' },
        ],
        correctAnswer: 'argument from ignorance',
        topic: 'logical-fallacies',
        explanation: 'The argument from ignorance (argumentum ad ignorantiam) claims something is true because it hasn\'t been proven false, or vice versa. The burden of proof lies on the person making the claim, not the skeptic.',
        interactionType: 'hover-reveal',
      },
    ],
  },

  // ─── 15. Financial Literacy ──────────────────────────────────
  {
    name: 'Financial Literacy',
    description: 'Master the essentials of personal finance — budgeting, investing, interest, and making smart money decisions.',
    enhances: 'Financial Planning, Numeracy, Decision Making',
    example: 'If you invest $100 at 10% annual interest, how much will you have after one year?',
    type: 'cognitive',
    difficulty: 'medium',
    topic: 'financial',
    questionBank: [
      {
        questionText: 'If you invest $1,000 at 5% simple annual interest, how much interest do you earn after 3 years?',
        options: ['$150', '$50', '$300', '$500'],
        correctAnswer: '$150',
        topic: 'compound-interest',
        explanation: 'Simple interest = principal × rate × time = $1,000 × 0.05 × 3 = $150. Simple interest does not compound — you earn the same amount each year on the original principal.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'A "bear market" means stock prices are generally:',
        options: ['Falling', 'Rising', 'Staying flat', 'Volatile'],
        correctAnswer: 'Falling',
        topic: 'investing',
        explanation: 'A bear market is defined as a decline of 20% or more from recent highs. Bull market = rising. The terms come from how bears and bulls attack: bears swipe downward, bulls thrust upward.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'The Rule of 72 says: to find how long money doubles, divide 72 by the:',
        options: ['Interest rate', 'Investment amount', 'Number of years', 'Inflation rate'],
        correctAnswer: 'Interest rate',
        topic: 'compound-interest',
        explanation: 'The Rule of 72: Years to double ≈ 72 / annual interest rate. At 6%, money doubles in ~12 years (72/6 = 12). At 9%, it doubles in ~8 years. A quick mental math tool for compound growth.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What is the recommended percentage of income to save for retirement?',
        options: ['10-15%', '5-10%', '20-25%', '1-5%'],
        correctAnswer: '10-15%',
        topic: 'budgeting',
        explanation: 'Most financial advisors recommend saving 10-15% of your pre-tax income for retirement. The earlier you start, the more compound interest works in your favor — $5,000 at 25 grows to far more than $10,000 at 35.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What does "APR" stand for in loans and credit cards?',
        options: ['Annual Percentage Rate', 'Applied Payment Rate', 'Annual Payment Return', 'Average Percentage Return'],
        correctAnswer: 'Annual Percentage Rate',
        topic: 'budgeting',
        explanation: 'APR is the annual cost of borrowing including interest and fees, expressed as a percentage. A 20% APR on a $1,000 balance means you pay about $200/year in interest if the balance stays constant.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'If inflation is 3% and your savings account earns 1%, your purchasing power is:',
        options: ['Decreasing by 2% per year', 'Increasing by 4% per year', 'Decreasing by 3% per year', 'Staying the same'],
        correctAnswer: 'Decreasing by 2% per year',
        topic: 'inflation',
        explanation: 'Real return = nominal return - inflation. At 1% interest with 3% inflation, your real return is -2%, meaning your money buys 2% less each year. This is why keeping all savings in low-interest accounts loses purchasing power over time.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What is the main advantage of a diversified investment portfolio?',
        options: ['Reduces risk by spreading across assets', 'Guarantees higher returns', 'Eliminates all losses', 'Requires no management'],
        correctAnswer: 'Reduces risk by spreading across assets',
        topic: 'investing',
        explanation: 'Diversification spreads risk across different assets (stocks, bonds, real estate, etc.). When one asset class drops, others may rise or hold steady. "Don\'t put all your eggs in one basket."',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'A credit score primarily measures:',
        options: ['How likely you are to repay debt', 'How much money you have', 'Your total net worth', 'Your income level'],
        correctAnswer: 'How likely you are to repay debt',
        topic: 'budgeting',
        explanation: 'A credit score (300-850 in the US) predicts the likelihood you\'ll repay borrowed money. Factors: payment history (35%), amounts owed (30%), length of history (15%), new credit (10%), credit mix (10%). Higher scores = lower interest rates.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What does "compound interest" mean?',
        options: ['Earning interest on your interest', 'Simple interest paid yearly', 'Interest paid only on principal', 'Interest that decreases over time'],
        correctAnswer: 'Earning interest on your interest',
        topic: 'compound-interest',
        explanation: 'Compound interest means you earn interest on both the original amount AND the accumulated interest. Einstein reportedly called it the "eighth wonder of the world." The earlier you start saving, the more powerful compounding becomes.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What is the 50/30/20 budget rule?',
        options: ['50% needs, 30% wants, 20% savings', '50% savings, 30% needs, 20% wants', '50% wants, 30% savings, 20% needs', '50% food, 30% housing, 20% transport'],
        correctAnswer: '50% needs, 30% wants, 20% savings',
        topic: 'budgeting',
        explanation: 'The 50/30/20 rule: 50% of after-tax income for needs (housing, food, utilities), 30% for wants (entertainment, dining out), and 20% for savings and debt repayment. A simple framework for balanced budgeting.',
        interactionType: 'multiple-choice',
      },
    ],
  },

  // ─── 16. Programming Logic ──────────────────────────────────
  {
    name: 'Programming Logic',
    description: 'Develop computational thinking — break down problems, design algorithms, trace code, and think like a programmer.',
    enhances: 'Logic, Problem Solving, Computational Thinking',
    example: 'What does this code output? print(2 + 3 * 4)',
    type: 'cognitive',
    difficulty: 'hard',
    topic: 'programming',
    questionBank: [
      {
        questionText: 'What is the output of: print(2 + 3 * 4)',
        options: ['14', '20', '9', '24'],
        correctAnswer: '14',
        topic: 'control-flow',
        explanation: 'Operator precedence: multiplication before addition. 3 × 4 = 12, then 2 + 12 = 14. In programming, * (multiply) always happens before + (add), just like in math.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'A variable x = 5. Then x = x + 3. What is x now?',
        options: ['8', '5', '3', '15'],
        correctAnswer: '8',
        topic: 'algorithms',
        explanation: 'x = x + 3 means: take the current value of x (5), add 3, and store the result back into x. So x = 5 + 3 = 8. This is called assignment — the = sign means "set to," not "equals."',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What does this loop do? for (i = 0; i < 5; i++) { print(i); }',
        options: ['Prints 0,1,2,3,4', 'Prints 1,2,3,4,5', 'Prints 0,1,2,3,4,5', 'Prints 1,2,3,4'],
        correctAnswer: 'Prints 0,1,2,3,4',
        topic: 'control-flow',
        explanation: 'The loop starts at i=0, runs while i < 5, and increments by 1 each time. So it prints 0, 1, 2, 3, 4. The condition i < 5 means it stops before reaching 5.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What is the bug in this code? if (x = 10) { print("x is 10"); }',
        options: ['Should be == not =', 'Missing parenthesis', 'Wrong variable name', 'No bug'],
        correctAnswer: 'Should be == not =',
        topic: 'debugging',
        explanation: 'In most languages, = is assignment (sets x to 10) while == is comparison (checks if x equals 10). Using = in a condition always evaluates as true because it assigns 10 to x.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What is an "array"?',
        options: ['A list of items stored in order', 'A type of loop', 'A conditional statement', 'A programming language'],
        correctAnswer: 'A list of items stored in order',
        topic: 'data-structures',
        explanation: 'An array is a data structure that holds multiple values in a specific order, accessible by index (position). myArray[0] gets the first item. Think of it like numbered boxes in a row.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Type the term for a function that calls itself:',
        correctAnswer: 'recursion',
        topic: 'algorithms',
        explanation: 'Recursion is when a function calls itself to solve smaller instances of the same problem. Classic examples: calculating factorials, traversing file directories, the Fibonacci sequence.',
        interactionType: 'text-input',
      },
      {
        questionText: 'In debugging, what is a "breakpoint"?',
        options: ['A pause point to inspect code state', 'A syntax error', 'The end of the program', 'A variable name'],
        correctAnswer: 'A pause point to inspect code state',
        topic: 'debugging',
        explanation: 'A breakpoint pauses program execution at a specific line so you can inspect variables, memory, and flow. It is one of the most powerful debugging tools.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What is the time complexity of finding an item in a sorted list using binary search?',
        options: ['O(log n)', 'O(n)', 'O(1)', 'O(n²)'],
        correctAnswer: 'O(log n)',
        topic: 'algorithms',
        explanation: 'Binary search repeatedly splits the sorted list in half, eliminating half the remaining items each time. With 1,000 items, it takes ~10 steps (2¹⁰ = 1024). With 1,000,000 items, only ~20 steps. That is logarithmic time — O(log n).',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Arrange these operations from FASTEST to SLOWEST: Array lookup, Sorting 1000 items, Searching 1000 items unsorted',
        puzzleType: 'sequence-order',
        items: ['Array lookup', 'Searching 1000 items unsorted', 'Sorting 1000 items'],
        correctAnswer: 'Array lookup,Searching 1000 items unsorted,Sorting 1000 items',
        topic: 'computational-thinking',
        explanation: 'Array lookup is O(1) — instant. Searching an unsorted list is O(n) — up to 1000 steps. Sorting is O(n log n) — about 10,000 operations. Understanding algorithmic efficiency helps you write better code.',
        interactionType: 'puzzle',
      },
      {
        questionText: 'What does "DRY" stand for in programming?',
        options: ['Don\'t Repeat Yourself', 'Develop Rapidly Yesterday', 'Debug Runtime Yields', 'Data Retrieval Yes'],
        correctAnswer: 'Don\'t Repeat Yourself',
        topic: 'computational-thinking',
        explanation: 'DRY is a fundamental principle: every piece of knowledge should have a single, unambiguous representation. Instead of copying code, create reusable functions. This reduces bugs and makes maintenance easier.',
        interactionType: 'multiple-choice',
      },
    ],
  },

  // ─── 17. General Knowledge ──────────────────────────────────
  {
    name: 'General Knowledge',
    description: 'Build a broad foundation of fascinating facts across science, history, geography, and culture.',
    enhances: 'Cultural Literacy, Curiosity, Memory',
    example: 'What is the largest organ in the human body?',
    type: 'cognitive',
    difficulty: 'easy',
    topic: 'general-knowledge',
    questionBank: [
      {
        questionText: 'What is the largest organ in the human body?',
        options: ['Skin', 'Liver', 'Brain', 'Heart'],
        correctAnswer: 'Skin',
        topic: 'science-facts',
        explanation: 'The skin is the largest organ, weighing about 8-10 pounds and covering about 22 square feet. It serves as a protective barrier, regulates temperature, and provides sensory information.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Which country has the most natural lakes?',
        options: ['Canada', 'USA', 'Russia', 'Brazil'],
        correctAnswer: 'Canada',
        topic: 'geography-facts',
        explanation: 'Canada has over 60% of the world\'s natural lakes — more than 60,000 lakes larger than 0.5 square miles. It contains about 20% of the world\'s fresh water.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Who was the first person to walk on the Moon?',
        options: ['Neil Armstrong', 'Buzz Aldrin', 'Yuri Gagarin', 'John Glenn'],
        correctAnswer: 'Neil Armstrong',
        topic: 'history-facts',
        explanation: 'Neil Armstrong stepped onto the Moon on July 20, 1969, during the Apollo 11 mission. His famous words: "That\'s one small step for a man, one giant leap for mankind."',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What is the most widely spoken language in the world by total speakers (native + second language)?',
        options: ['English', 'Mandarin Chinese', 'Spanish', 'Hindi'],
        correctAnswer: 'English',
        topic: 'culture',
        explanation: 'English has about 1.5 billion total speakers (including second-language learners). Mandarin has the most native speakers (~920 million), but English has the most total speakers worldwide.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What gas do plants absorb from the atmosphere during photosynthesis?',
        options: ['Carbon dioxide', 'Oxygen', 'Nitrogen', 'Hydrogen'],
        correctAnswer: 'Carbon dioxide',
        topic: 'science-facts',
        explanation: 'Plants absorb carbon dioxide (CO₂) and water (H₂O), using sunlight to produce glucose and oxygen. This is why forests are called "the lungs of the Earth."',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What is the longest mountain range on Earth?',
        options: ['The Andes', 'The Himalayas', 'The Rockies', 'The Alps'],
        correctAnswer: 'The Andes',
        topic: 'geography-facts',
        explanation: 'The Andes stretch about 7,000 km (4,300 miles) along the western coast of South America, making them the longest continental mountain range. The Himalayas are the tallest, but not the longest.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'In what year did World War II end?',
        options: ['1945', '1944', '1946', '1943'],
        correctAnswer: '1945',
        topic: 'history-facts',
        explanation: 'WWII ended in 1945 with Germany surrendering in May (VE Day) and Japan surrendering in September (VJ Day). It was the deadliest conflict in human history.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Type the unit of measurement for electrical resistance:',
        correctAnswer: 'ohm',
        topic: 'science-facts',
        explanation: 'The ohm (symbol: Ω) is the SI unit of electrical resistance, named after German physicist Georg Ohm. 1 ohm = 1 volt/ampere. A material with high resistance restricts the flow of electricity.',
        interactionType: 'text-input',
      },
      {
        questionText: 'Which famous structure is located in Agra, India?',
        options: ['Taj Mahal', 'Great Wall', 'Eiffel Tower', 'Colosseum'],
        correctAnswer: 'Taj Mahal',
        topic: 'culture',
        explanation: 'The Taj Mahal in Agra, India, was built by Emperor Shah Jahan in memory of his wife Mumtaz Mahal. It took about 20,000 workers and 22 years to complete (1632-1653).',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'What is the smallest bone in the human body?',
        options: ['Stapes (in the ear)', 'Phalanx (in the finger)', 'Patella (kneecap)', 'Coccyx (tailbone)'],
        correctAnswer: 'Stapes (in the ear)',
        topic: 'science-facts',
        explanation: 'The stapes (stirrup bone) in the middle ear is the smallest bone in the human body — about 3mm long. It transmits sound vibrations from the eardrum to the inner ear.',
        interactionType: 'multiple-choice',
      },
    ],
  },

  // ─── 18. Reading Comprehension ──────────────────────────────
  {
    name: 'Reading Comprehension',
    description: 'Sharpen your ability to understand, analyze, and interpret written passages — a critical skill for learning and communication.',
    enhances: 'Critical Reading, Analysis, Vocabulary',
    example: 'Read a short passage and answer questions about its meaning and implications.',
    type: 'cognitive',
    difficulty: 'hard',
    topic: 'reading',
    questionBank: [
      {
        questionText: 'Passage: "She walked into the room, her shoulders slumped, eyes fixed on the floor." What is the most likely emotion?',
        options: ['Sadness or defeat', 'Excitement', 'Anger', 'Surprise'],
        correctAnswer: 'Sadness or defeat',
        topic: 'inference',
        explanation: 'Reading body language — slumped shoulders and downcast eyes — allows us to infer emotions not explicitly stated. This is the foundation of inferential reading: understanding what the text implies without saying directly.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Passage: "The researchers spent five years collecting data from 10,000 participants before drawing any conclusions." The main idea is:',
        options: ['Research requires patience and rigorous methodology', 'Five years is too long', '10,000 is a large sample', 'Conclusions are not important'],
        correctAnswer: 'Research requires patience and rigorous methodology',
        topic: 'main-idea',
        explanation: 'The main idea synthesizes the details (5 years, 10,000 participants) into the broader point — thorough research takes time and careful methodology. Not just "they had a lot of participants."',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Passage: "The new policy was implemented with surprising speed. Critics called it reckless; supporters called it decisive." The author\'s tone is:',
        options: ['Neutral/balanced', 'Critical', 'Supportive', 'Sarcastic'],
        correctAnswer: 'Neutral/balanced',
        topic: 'authors-purpose',
        explanation: 'The author presents both sides without signaling which is correct — "critics called it reckless; supporters called it decisive." A neutral tone presents opposing views without endorsing either.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Passage: "The old house had stood for a century, its foundation slowly crumbling. Still, it refused to fall." The crumbling foundation is used as:',
        options: ['A metaphor for resilience', 'A literal description', 'A historical fact', 'An exaggeration'],
        correctAnswer: 'A metaphor for resilience',
        topic: 'text-analysis',
        explanation: 'The crumbling foundation represents decay, but "refused to fall" personifies the house as determined. Together they create a metaphor for resilience and endurance in the face of decline.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Passage: "Photosynthesis is the process by which plants convert sunlight into chemical energy." The word "convert" most nearly means:',
        options: ['Transform', 'Transport', 'Consume', 'Create'],
        correctAnswer: 'Transform',
        topic: 'vocabulary-in-context',
        explanation: 'In this context, "convert" means to change from one form to another — sunlight (light energy) is transformed into glucose (chemical energy). "Transform" is the closest match.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Passage: "Despite the heavy rain, the parade went on. Crowds lined the streets under umbrellas, cheering just as loudly." What can be inferred about the community?',
        options: ['They are determined and spirited', 'They dislike parades', 'They only go out in good weather', 'They were forced to attend'],
        correctAnswer: 'They are determined and spirited',
        topic: 'inference',
        explanation: 'The fact that crowds showed up and cheered loudly despite rain shows determination and community spirit. "Despite" signals that rain would normally be a deterrent, but these people attended anyway.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Passage: "First, preheat the oven to 350°F. Then, mix the dry ingredients separately from the wet. Finally, combine and bake for 30 minutes." What type of text is this?',
        options: ['Instructions/procedure', 'Narrative', 'Persuasive', 'Expository'],
        correctAnswer: 'Instructions/procedure',
        topic: 'authors-purpose',
        explanation: 'The text gives sequential steps (first, then, finally) using commands (preheat, mix, combine) to guide the reader through a process. This is a procedural or instructional text.',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Type the term for a conclusion reached based on evidence and reasoning rather than explicit statement:',
        correctAnswer: 'inference',
        topic: 'text-analysis',
        explanation: 'An inference is a logical conclusion based on evidence in the text combined with the reader\'s own knowledge. "Reading between the lines" — the text implies, you infer.',
        interactionType: 'text-input',
      },
      {
        questionText: 'Passage: "There are three types of rocks: igneous, sedimentary, and metamorphic." What is the organizational pattern?',
        options: ['Classification', 'Cause and effect', 'Chronological', 'Compare and contrast'],
        correctAnswer: 'Classification',
        topic: 'main-idea',
        explanation: 'The text categorizes rocks into three distinct types. Classification organizes information by grouping items into categories. This is different from compare/contrast (which finds similarities and differences).',
        interactionType: 'multiple-choice',
      },
      {
        questionText: 'Passage: "The results were disappointing — but perhaps that is exactly what we needed to learn." The dash suggests:',
        options: ['A shift in perspective', 'A list follows', 'A question is coming', 'The sentence is over'],
        correctAnswer: 'A shift in perspective',
        topic: 'text-analysis',
        explanation: 'The dash creates a pause and signals a contrast or shift. The first part says "disappointing," but after the dash comes a reframing — the disappointment was actually valuable. The dash marks the pivot in perspective.',
        interactionType: 'multiple-choice',
      },
    ],
  },
];

async function seed() {
  const batch = db.batch();
  const ids = [
    'pattern-recognition',
    'vocabulary-builder',
    'mental-math',
    'memory-recall',
    'logic-puzzles',
    'word-association',
    'spatial-reasoning',
    'quick-reflexes',
    'creative-thinking',
    'emotional-intelligence',
    'data-interpretation',
    'language-learning',
    'attention-focus',
    'critical-thinking',
    'financial-literacy',
    'programming-logic',
    'general-knowledge',
    'reading-comprehension',
  ];

  console.log(`Seeding ${skills.length} skills with ${skills.reduce((sum, s) => sum + s.questionBank.length, 0)} total questions...`);

  for (let i = 0; i < skills.length; i++) {
    const ref = db.collection('skills').doc(ids[i]);
    batch.set(ref, skills[i]);
  }

  await batch.commit();
  console.log('Seed complete! Skills added to Firestore.');
  console.log('Document IDs:', ids.join(', '));
  console.log('\nSkills breakdown:');
  skills.forEach((s, i) => {
    const types = [...new Set(s.questionBank.map((q) => q.interactionType))].join(', ');
    const topics = [...new Set(s.questionBank.map((q) => q.topic))].join(', ');
    console.log(`  ${i + 1}. ${s.name} — ${s.questionBank.length} questions [${types}] — Topics: ${topics}`);
  });
}

seed()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error('Seed failed:', err);
    process.exit(1);
  });
